# NumPy for Quantum Mathematics



Use `import numpy as np` at the top of your work. Write your code in the empty cells provided.

In [1]:
import numpy as np

## Question 1, Complex Numbers

Let

$$z = 5 - 2i$$

Using NumPy, compute and print the real part, the imaginary part, the modulus, and the conjugate of $z$.

Then verify the identity

$$|z|^2 = z z^*$$

by computing both sides and printing them.

In [2]:
# Your code here
z=5-2j
real_part = np.real(z)
imaginary_part = np.imag(z)
modulus = np.abs(z)
conjugate = np.conjugate(z)
print("Real part:", real_part)
print("Imaginary part:", imaginary_part)
print("Modulus:", modulus)
print("Conjugate:", conjugate)
value_1=np.abs(z)**2
value_2=z*np.conj(z)
print("value_1:",value_1)
print("value_2:",value_2)
print(np.allclose(value_1,value_2))


Real part: 5.0
Imaginary part: -2.0
Modulus: 5.385164807134504
Conjugate: (5+2j)
value_1: 28.999999999999996
value_2: (29+0j)
True


## Question 2, Vectors and Kets

Define the two basic qubit states

$$|0\rangle = \begin{pmatrix} 1 \\ 0 \end{pmatrix}, \qquad |1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$$

as NumPy arrays.

Using these, construct the state

$$|-\rangle = \frac{1}{\sqrt{2}} \big(|0\rangle - |1\rangle\big)$$

Print the resulting vector, then compute and print its norm. The norm should be very close to one.

In [3]:
# Your code here
ket_0=np.array([1,0])
ket_1=np.array([0,1])
ket_minus=1/np.sqrt(2)*(ket_0-ket_1)
print("ket_minus:",ket_minus)
norm=np.linalg.norm(ket_minus)
print("norm:",norm)


ket_minus: [ 0.70710678 -0.70710678]
norm: 0.9999999999999999


## Question 3, Inner Products

Let

$$u = \begin{pmatrix} 2 - i \\ 3 \end{pmatrix}, \qquad v = \begin{pmatrix} 1 \\ 2 + i \end{pmatrix}$$

Compute $\langle u, v \rangle$ using the correct NumPy function for a quantum mechanical inner product.

Then check whether $u$ and $v$ are orthogonal.

In [4]:
# Your code here
u=np.array([2-1j,3])
v=np.array([1,2+1j])
inner_product=np.vdot(u,v)
print("inner_product:",inner_product)
print(np.vdot(u,v)==0)




inner_product: (8+4j)
False


## Question 4, Matrices

Let

$$A = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \qquad B = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}$$

Compute and print the following four quantities.

1. $A + B$
2. The true matrix product $AB$
3. The Hermitian transpose of $A$
4. $A$ multiplied by the vector $|1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$

In [5]:
# Your code here
A=np.array([[0,1],[1,0]])
B=np.array([[1,0],[0,-1]])
sum_AB=A+B
print("sum_AB:",sum_AB)
product_AB=A @ B
print("product_AB:",product_AB)
hermitian_transpose_A=np.conj(A.T)
print("hermitian_transpose_A:",hermitian_transpose_A)
ket_1=np.array([0,1])
product_A_ket_1=A @ ket_1
print("product_A_ket_1:",product_A_ket_1)



sum_AB: [[ 1  1]
 [ 1 -1]]
product_AB: [[ 0 -1]
 [ 1  0]]
hermitian_transpose_A: [[0 1]
 [1 0]]
product_A_ket_1: [1 0]


## Question 5, Eigenvalues and Eigenvectors

Let

$$X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$

This is known as the Pauli X gate.

Compute the eigenvalues and eigenvectors of $X$ using NumPy.

Then pick the first eigenvalue and its corresponding eigenvector, and verify the equation $Xv = \lambda v$ by computing both sides and printing them.

In [6]:
# Your code here
X=np.array([[0,1],[1,0]])
eigenvalues,eigenvectors=np.linalg.eigh(X)
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)
first_eigenvalue=eigenvalues[0]
first_eigenvector=eigenvectors[:,0]
print("first_eigenvalue:",first_eigenvalue)
print("first_eigenvector:",first_eigenvector)

left_side=X@first_eigenvector
right_side=first_eigenvalue*first_eigenvector
print("left_side:",left_side)
print("right_side:",right_side)
print(np.allclose(left_side,right_side))


eigenvalues: [-1.  1.]
eigenvectors: [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
first_eigenvalue: -1.0
first_eigenvector: [-0.70710678  0.70710678]
left_side: [ 0.70710678 -0.70710678]
right_side: [ 0.70710678 -0.70710678]
True


## Question 6, Tensor Products

Using the kets $|0\rangle$ and $|1\rangle$ from Question 2, compute the tensor product

$$|0\rangle \otimes |1\rangle$$

Print the resulting vector and state its dimension.

Then compute the tensor product of the identity matrix and the Pauli X gate from Question 5, that is

$$I \otimes X$$

Print the resulting matrix and state its shape.

In [9]:
# Your code here
ket_0=np.array([1,0])
ket_1=np.array([0,1])
tensor_product=np.kron(ket_0,ket_1)
print("tensor_product:",tensor_product)
print("dimension:",np.ndim(tensor_product))
X=np.array([[0,1],[1,0]])
tensor_product_2=np.kron(np.eye(2),X)
print("tensor_product_2:",tensor_product_2)
print("shape:",np.shape(tensor_product_2))

tensor_product: [0 1 0 0]
dimension: 1
tensor_product_2: [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
shape: (4, 4)


## Question 7, Unitarity Checks

Write a function called `is_unitary` that takes a matrix as input and returns `True` if the matrix is unitary, and `False` otherwise. Remember to use `np.allclose` rather than checking for exact equality.

Test your function on the following two matrices.

$$X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \qquad C = \begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix}$$

State in a short comment which one is unitary and which one is not, based on your function's output.

In [10]:
# Your code here
def is_unitary(matrix):
    if np.allclose(matrix @ np.conj(matrix.T),np.eye(np.shape(matrix)[0])):
        return True
    else:
        return False
X=np.array([[0,1],[1,0]])
C=np.array([[1,2],[0,1]])
print("is_unitary(X):",is_unitary(X))
print("is_unitary(C):",is_unitary(C))


is_unitary(X): True
is_unitary(C): False
